### ISSUE TITLE
Review exception handling across project

### ISSUE THREAD

**Issue by jrriehl** [fetchai/uAgents#15]
We need better exception handling, particularly when errors occur inside message and interval handlers. These should generally not cause the agent to fail.

**Comment by Archento** [comment]
I would like to bump this issue since I'm continuously running into problems where agents just starting to act weirdly after being unable to send messages to other agents.
The terminal is also being spammed with error messages and this is even more pressing when scaling the agent communication / using the search&discovery mechanisms and a large portion of agents that support a specific protocol are simply not reachable.

**Comment by Archento** [comment]
A lot has changed since last year and the overall code quality and resiliency has improved.
So I'll close this issue now as it doesn't have a definition of done and we will tackle upcoming errors individually, i.e. create tickets for errors that come up.
